### PR TITLE
Do not assigned addresses to non-alloc sections (and Program Headers)

### PR DESCRIPTION
**Pull request by marxin**
Fixes: #73

### CODE REVIEW

**Comment by marxin** [comment]
@davidlattimore For `integration_test::program_name_12___internal_syms_c__` I face the following problem:

```
readelf -SW /home/marxin/Programming/wild/wild/tests/build/internal-syms.c-default.wild
There are 10 section headers, starting at offset 0x120:

Section Headers:
  [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            0000000000000000 000000 000000 00      0   0  0
  [ 1] .phdr             NULL            0000000000400040 000040 000000 00   A  0   0  0
  [ 2] .shdr             NULL            0000000000400120 000120 000000 00   A  0   0  0
  [ 3] .eh_frame         PROGBITS        00000000004003a0 0003a0 000070 00   A  0   0  8
  [ 4] .text             PROGBITS        0000000000401410 000410 000063 00  AX  0   0  1
  [ 5] .rela.plt         RELA            0000000000402478 000478 000000 18  AI  8   0  1
  [ 6] .comment          PROGBITS        0000000000000000 000478 000035 01  MS  0   0  1
  [ 7] .shstrtab         STRTAB          0000000000000000 0004ad 00004a 00      0   0  1
  [ 8] .symtab           SYMTAB          0000000000000000 0004f8 0000a8 18      9   3  8
  [ 9] .strtab           STRTAB          0000000000000000 0005a0 00004e 00      0   0  1
```

As seen `rela.plt` is empty and thus we produce a segment with **zero size**:
`LOAD           0x000478 0x0000000000402478 0x0000000000402478 0x000000 0x000000 RW  0x1000`

That's something the dynamic linker is unhappy about. The section itself is preserved because it contains 2 symbols that are referenced:

```
     4: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND __rela_iplt_start
     5: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND __rela_iplt_end

```

and so the following condition is met:
https://github.com/davidlattimore/wild/blob/de472c8f2e25559497e452f608f8ec7a1f1a4a34/wild_lib/src/layout.rs#L2411

Do you have idea how to address that?

**Comment by marxin** [comment]
And the second failure comes from the linker-diff of `integration_test::program_name_25___libc_integration_c__` that might be again related to an empty section that Wild keeps:
`[ 6] .preinit_array       PREINIT_ARRAY 0000000000000000 00030c54 00000000  0        0   0  1`

```
  wild 0x00448a2e 48 83 3d 7a 8f 07 00 00 cmpq $0,0x790D2  // Cmp_rm64_imm8(0x4c19b0) GOT(__preinit_array_start) GOT(__preinit_array_end)
  ld   0x0040426e 48 83 3d 0a dd 0b 00 00 cmpq $0,0xBDE62  // Cmp_rm64_imm8(0x4c1f80) POINTER-TO(byte in (RW))
  ORIG            48 83 3d 00 00 00 00 00 cmpq $0,0x158  // R_X86_64_GOTPCREL -> `__pthread_initialize_minimal` -5
```

And suggestion what can be wrong?

**Comment by davidlattimore** [comment]
For `program_name_12___internal_syms_c__`, it looks like the test was wrong. It actually was dereferencing the pointers that the comment said it shouldn't - it just happened to work before. I've pushed a fix for the test.

**Comment by davidlattimore** [comment]
For the linker-diff failure, I think it's a problem in linker-diff rather than a problem in the linker. There's a bunch of work needed to improve the asm diffing. I think part of the problem in this case is that the instructions in question have have two operands, a 4 byte one and a 1 byte one. This results in the addend being 5, but linker-diff is probably assuming that it'll be 4. At least that's my guess. Previously probably both GNU ld and Wild's outputs were effectively failing to match anything and two non-matches are considered OK. But now Wild, by chance is happening to match to a symbol (or a couple of symbols) and that's causing a failure.

One possible fix would be to say that if the reference linker fails to match (`POINTER-TO(byte in (RW))`), then we should accept anything from Wild.

A bigger change would be to improve the matching to take better advantage of information from the original relocation.

It's also possible if we shift some sections around that we'll get lucky and the test will pass - although linker-diff will likely still need these fixes eventually.

It looks like you're changing a few things with this PR. There are sections moving about, additional debug sections being output and sections that previously had addresses assigned not being assigned. One option might be to split this PR into a few commits that make smaller changes. It might be that the change that is actually triggering this isn't one that you need now.

**Comment by davidlattimore** [comment]
I think you could probably add it in `UnifiedInstruction::new`, just after the call to `extract_undefined_behaviour`. I'm off to bed. If you can't get it working and want me to look during my day tomorrow, let me know.

**Comment by marxin** [comment]
Please do it for me tomorrow, I'm finishing for today.

**Pull request merged**
